---
title: "Full_Video_Pipeline_Manual"
author: "Brandon Bowers"
date: "2025-03-13"
output: html_document
---

```{r}
library (glue)
library (stringr)
library(vroom)
library(ggplot2)
library(gtools)
```

#SET LOCATION OF DATA HERE
```{r}
WORKD = "C:\\Users\\Bvipe\\OneDrive - Walla Walla University\\Desktop\\Bowers_2025_Octopus_Vestibular"

datelist_u = c("7_24","7_26","7_28","7_30","8_1","8_3","8_5","8_7","8_9","8_11","8_13","8_15","8_17")

mantle_indecies = read.csv(paste0(WORKD,"\\Raw Data\\Octopus_Mantle_Measurements\\Mantle Indecies.csv"))

start_end_frames = read.csv(paste0(WORKD,"\\Raw Data\\Path_Analysis_Start_End_Frames.csv"))

OC_NUMS = c(1,2,4,5,7,8,9,10,11,12,13,14,16,17,18,19)
```

~~~~~~~~~~
#OCTOPUS BEARING BELOW
~~~~~~~~~~

#OCTOPUS Get files
```{r}
oc_get_file = function(WD,folder_date){ 
  wd = c(WD,"Raw Data\\Raw_Octopus_Label_Coordinates",folder_date)
  wd_path = stringr::str_c(wd, collapse = "/")
  in_files_list = list.files(wd_path, pattern = NULL, all.files = FALSE,
           full.names = FALSE, recursive = FALSE,
           ignore.case = FALSE, include.dirs = FALSE, no.. = FALSE)
  return(in_files_list)
}
```

#Read files
```{r}
oc_read_file = function(WD,folder_date,f){
  wd = c(WD,"Raw Data\\Raw_Octopus_Label_Coordinates",folder_date,f)
  fullpath = stringr::str_c(wd, collapse = "/")
  dat_tab = read.csv(fullpath, stringsAsFactors=FALSE)
  C_S_V = dat_tab
  return(dat_tab)
}
```

#OCTOPUS: Organize coordinates
```{r}
oc_organize_coordinates = function(dat_tab){
  len = nrow(dat_tab)
  
  frame_raw = dat_tab[3:len,3]
  frame = c()
  for (i in 1:length(frame_raw)){
    f = (unlist(strsplit(frame_raw[i], split='.jpg', fixed=TRUE))[1])
    frame = c(frame,f)
  }
  
  left_eye_x = dat_tab[3:len,4]
  left_eye_y = dat_tab[3:len,5]
  #left_eye_likelihood = dat_tab[3:len,4]
  left_eye = data.frame(left_eye_x,left_eye_y)
  
  right_eye_x = dat_tab[3:len,6]
  right_eye_y = dat_tab[3:len,7]
  #right_eye_likelihood = dat_tab[3:len,7]

  right_eye = data.frame(right_eye_x,right_eye_y)
  
  MT_x = dat_tab[3:len,8]
  MT_y = dat_tab[3:len,9]
  #MT_likelihood = dat_tab[3:len,10]
  mantle_tip = data.frame(MT_x,MT_y)
  
  coors = data.frame(frame,left_eye,right_eye,mantle_tip)
  coors$frame = as.numeric(as.character(coors$frame))
  ordered_coors = coors[order(coors$frame),]
  
  return(ordered_coors)
}
```

#OCTOPUS: Find Bearing
```{r}
oc_stat_bearing = function(coors){
  len = length(coors$left_eye_x)
  eye_bar_vectorsx = c()
  eye_bar_vectorsy = c()
  
  angles = c()
  
  frames = c()
  
  CX_pos = c()
  CY_pos = c()
  
  eye_bar_perp_vecx = c()
  eye_bar_perp_vecy = c()
  
  #always path from left eye to right
  for (i in 1:len){
    frame = 1
    #vec of eye bar
    bar_vecx = as.integer(coors$left_eye_x[i]) - as.integer(coors$right_eye_x[i])
    bar_vecy = as.integer(coors$left_eye_y[i]) - as.integer(coors$right_eye_y[i])
    
    eye_bar_vectorsx = c(eye_bar_vectorsx,bar_vecx)
    eye_bar_vectorsy = c(eye_bar_vectorsy,bar_vecy)
    
    c_x = (as.integer(coors$left_eye_x[i]) + as.integer(coors$right_eye_x[i])) / 2
    c_y = (as.integer(coors$left_eye_y[i]) + as.integer(coors$right_eye_y[i])) / 2
    
    CX_pos = c(CX_pos,c_x)
    CY_pos = c(CY_pos,c_y)
    
    frames = c(frames, frame)
    frame =+ 1
    
    #rotate vec 90 degrees (to right)
    perpvecx = (bar_vecx * cos(90)) - (bar_vecy * sin(90))
    perpvecy = (bar_vecx * sin(90)) + (bar_vecy * cos(90))
    
    dis = sqrt((perpvecx)**2 + (perpvecy)**2)
    
    perpvecx = perpvecx / dis
    perpvecy = perpvecy / dis
    
    nang = atan2(perpvecy,perpvecx)
    
    eye_bar_perp_vecx = c(eye_bar_perp_vecx, perpvecx)
    eye_bar_perp_vecy = c(eye_bar_perp_vecy, perpvecy)
    angles = c(angles,nang)
    center = data.frame(CX_pos,CY_pos)
  }
  
  return(data.frame(eye_bar_perp_vecx,eye_bar_perp_vecy,angles,center))
}
```

#OCTOPUS: Calc change in bearing (diff of (i - i+1))
```{r}
bearing_change = function(bearing_vecs){
  len = length(bearing_vecs$eye_bar_perp_vecx)

  bearing_x_change = c()
  bearing_y_change = c()
  angle_change = c()
  move_dir = c()
  distance = c()
  speed = c()

  for (i in 1:len-1){
    bearing_x_dif = bearing_vecs$eye_bar_perp_vecx[i+1] - bearing_vecs$eye_bar_perp_vecx[i]
    bearing_y_dif = bearing_vecs$eye_bar_perp_vecy[i+1] - bearing_vecs$eye_bar_perp_vecy[i]
    angle_dif = bearing_vecs$angles[i+1] - bearing_vecs$angles[i]
    
    dis = sqrt((bearing_vecs$CX_pos[i] - bearing_vecs$CX_pos[i+1])^2 + (bearing_vecs$CY_pos[i] - bearing_vecs$CY_pos[i+1])^2)
    spd = dis / (1/6) #dis in pixels per sec
    
    bearing_x_change = c(bearing_x_change,bearing_x_dif)
    bearing_y_change = c(bearing_y_change,bearing_y_dif)  
    angle_change = c(angle_change,angle_dif)
    distance = c(distance,dis)
    speed = c(speed,spd)
  }
  
  for (i in 1:len-1){
    xdif = (bearing_vecs$CX_pos[i+1] - bearing_vecs$CX_pos[i])
    ydif = (bearing_vecs$CY_pos[i+1]- bearing_vecs$CY_pos[i])
    MD = atan2(ydif,xdif)
    move_dir = c(move_dir,MD)
  }
  
  return(data.frame(bearing_x_change,bearing_y_change,distance, speed, angle_change, move_dir))
}
```

#OCTOPUS: Calc distance/body length
```{r}
bod_l_speed = function(file_title,b_change,bearing_vecs,mant_index){
  count = 1
  
  for (i in OC_NUMS){
    ocnum = c("O",as.character(i),".csv")
    TF = str_detect(file_title, paste(ocnum, collapse = ""))

    m_dex = mant_index$INDEX[count]
    count =+ 1
  }
  
  len = length(b_change$speed)
  Speed_per_Bodylength = c()
  for (j in 1:len){
    new_spd = b_change$speed[j] / m_dex
    Speed_per_Bodylength = c(Speed_per_Bodylength,new_spd)
  }
  
  #find dif in direction of movement and bearing
  Bearing_Movedir_Dif = c()

  for (i in 1:len){
    bear_move_dif = bearing_vecs$angles[i] - b_change$move_dir[i] 
    Bearing_Movedir_Dif = c(Bearing_Movedir_Dif,bear_move_dif)
  }
  
    Distance = b_change$distance
    Speed_Pixels = b_change$speed
    Bearing_Change = b_change$angle_change
    Dir_of_Movement = b_change$move_dir
    
    
  
  #return( data.frame(b_change$distance,b_change$speed,speed_per_bodylength,b_change$angle_change,b_change$move_dir, Bearing_Movedir_Dif))
  return( data.frame(Distance,Speed_Pixels,Speed_per_Bodylength,Bearing_Change,Dir_of_Movement, Bearing_Movedir_Dif))
}
```

#MAIN LOOP FOR BEARING CHANGE (passed the date in two formats)
```{r}
main_loop = function(DATE,WORKD){
  #OCTOPUS
    #FIND FILES
  in_files_list = oc_get_file(WORKD,DATE)
  #print(in_files_list)
  
    #READ FILES
  for (i in in_files_list) {
    raw_csv = oc_read_file(WORKD,DATE,i)
  
    coor_temp = oc_organize_coordinates(raw_csv)
    
    bearing_vecs = oc_stat_bearing(coor_temp)  #HOW TO DEAL WITH GAPS OF MISSING FRAMES
    
    b_change = bearing_change(bearing_vecs)
    
    b_change_plu_s_peed= bod_l_speed(i,b_change,bearing_vecs,mantle_indecies)
    
  #Rename variables
    #Raw Single Frame Data  
    Bearing = bearing_vecs$angles
    Center_Position_x = bearing_vecs$CX_pos
    Center_Position_y = bearing_vecs$CY_pos
    
    #Between Frame Metrics
    Bearing_Change = c(b_change_plu_s_peed$Bearing_Change)
    Move_Dir = c(b_change_plu_s_peed$Dir_of_Movement)
    Bearing_Move_Diff = c(b_change_plu_s_peed$Bearing_Movedir_Dif)
    Speed_Pixels = c(b_change_plu_s_peed$Speed_Pixels)
    Speed_per_MI = c(b_change_plu_s_peed$Speed_per_Bodylength)

    Processed = data.frame(Move_Dir,Bearing_Change,Bearing_Move_Diff,Speed_Pixels,Speed_per_MI)
    
    #write.csv(b_change,paste0(WORKD,"\\Processed Data\\Full Video Results\\",DATE,"\\Raw_",i))
    write.csv(b_change_plu_s_peed,paste0(WORKD,"\\Processed Data\\Full Video Results\\",DATE,"\\Processed_",i))
  }
}
```

#Loop to itertively run the main loop for each date
```{r}
for (i in 1:length(datelist_u)){
  DATE = datelist_u[i]
  print(DATE)
  path = paste0(WORKD,"\\Processed Data\\Full Video Results")
  newfolder = DATE
  ifelse(!dir.exists(file.path(path, newfolder)), dir.create(file.path(path,newfolder)), FALSE)
  
  main_loop(DATE,WORKD)
}
```




