---
title: "Path_Analysis_Pipeline"
author: "Brandon Bowers"
date: "2025-03-13"
output: html_document
---
```{r}
library (glue)
library (stringr)
library(vroom)
library(ggplot2)
library(gtools)
```

#SET LOCATION OF DATA HERE
```{r}
datelist_u = c("7_24","7_26","7_28","7_30","8_1","8_3","8_5","8_7","8_9","8_11","8_13","8_15","8_17")
datelist = c("7/24","7/26","7/28","7/30","8/1","8/3","8/5","8/7","8/9","8/11","8/13","8/15","8/17")

WORKD = "C:\\Users\\Bvipe\\OneDrive - Walla Walla University\\Desktop\\Bowers_2025_Octopus_Vestibular"

mantle_indecies = read.csv(paste0(WORKD,"\\Raw Data\\Octopus_Mantle_Measurements\\Mantle Indecies.csv"))

start_end_frames = read.csv(paste0(WORKD,"\\Raw Data\\Path_Analysis_Start_End_Frames.csv"))

OC_NUMS = c(1,2,4,5,7,8,9,10,11,12,13,14,16,17,18,19)
```

#CRAB coordinates
```{r}
carap_coors = function(dat_tab){
  len = nrow(dat_tab)

  X = dat_tab[3:len,2]
  Y = dat_tab[3:len,3]
  lik = dat_tab[3:len,4]

  carap_cent_tot = data.frame(X,Y,lik)

  X10 = c()
  Y10 = c()
  lik10 = c()
  
  ticker = 0
  for (i in 1:len){
    if (ticker == 0){
      X10 = c(X10,carap_cent_tot$X[i])
      Y10 = c(Y10,carap_cent_tot$Y[i])
      lik10 = c(lik10,carap_cent_tot$lik[i])
      
      if (is.na(carap_cent_tot$X[i])){
        #print(carap_cent_tot$X[i])
      }
      ticker = 10
    } 
    else{
      ticker = ticker - 1
    }
  }
  
  carap_cent_10f = data.frame(X10,Y10,lik10)
  
  return(carap_cent_10f)
}
```

#PATH ANALYSIS
-----------------------------------------------------------------------------------------------------------------------------------------------------

#This function is passed the list of indecies and specific index of the current movement event in order to return tot_dis and ang_dev
```{r}
path_deviance = function(DATE,date_batch,ind){
  frames = c()
  total_movement_dis = c()
  angle_dev = c()
  bearing_movedir_diff = c()
  
  ocnum = start_end_frames$OCNUM[date_batch[ind]]

  ####
  #Read in relevant raw octopus coordinate file
  
  coordinates_file = paste0(WORKD,"\\Raw Data\\Raw_Octopus_Label_Coordinates\\",DATE,"\\",DATE,"_","O",ocnum,".csv")
  
  current_oc_coors_file = read.csv(coordinates_file,skip = 2)
  
  for (coor in 1:length(current_oc_coors_file$X.1)){
    current_oc_coors_file$X.1[coor] = unlist(strsplit(current_oc_coors_file$X.1[coor],".jpg")[1])
    current_oc_coors_file$X.1[coor] = as.numeric(current_oc_coors_file$X.1[coor])
  }

  ordered_curr_oc = current_oc_coors_file[order(as.numeric(current_oc_coors_file$X.1)),]
  ###
  
  ####
  #Read in relevant crab coordinate file
  
  crabcoordinates_file = paste0(WORKD,"\\Raw Data\\Raw_Crab_DLC_Label_Coordinates\\",DATE,"\\",DATE,"_","O",ocnum," - Made with ClipchampDLC_Resnet50_Thesis_Crab_9_25Sep25shuffle1_snapshot_010.csv")
  #Crab coordinates file contatains 60 frames per second, so must be filtered down to match the octopus data at 6 frames per second
  current_crab_coors_file = read.csv(crabcoordinates_file)
  current_crab_coors_file = carap_coors(current_crab_coors_file)
  ###
  
  #Calculate tot dis of path
    #find indecies of start and end frames in coordinate data
  index_count = 1
  movement_indecies = c()
  
  for (k in 1:length(ordered_curr_oc$X.1)){
    
    if (as.character(start_end_frames$START[date_batch[ind]]) == as.character(ordered_curr_oc$X.1[k])){
      start_index = index_count
      start_frame = as.character(start_end_frames$START[date_batch[ind]])
      index_count = index_count + 1
    }
    else if (as.character(start_end_frames$END[date_batch[ind]]) == as.character(ordered_curr_oc$X.1[k])){
      end_index = index_count
      end_frame = as.character(start_end_frames$END[date_batch[ind]])
      index_count = index_count + 1
    }
    
    else{
      index_count = index_count + 1
    }
  }
 
  #start index is the index position of the start of the movement, not the frame number of the start of the movement. Likewise, the list of movement indices are the index positions of the frame values within both crab and octopus tables.
  indee = start_index
  while (indee <= end_index){
    if (indee > end_index){
      print ("WRONG")
      break
    }
    else{
      movement_indecies = c(movement_indecies,indee) 
      frames = c(frames,ordered_curr_oc$X.1[indee])
    }
    indee = indee + 1
  } 

  #Re-find Center points
  centerx = c()
  centery = c()
  len = length(ordered_curr_oc$x)
  lx = ordered_curr_oc[1:len,4]
  ly = ordered_curr_oc[1:len,5]
  rx = ordered_curr_oc[1:len,6]
  ry = ordered_curr_oc[1:len,7]
  for (ind in movement_indecies){
    centx = ((as.numeric(lx[ind]) + as.numeric(rx[ind]))) / 2
    centy = ((as.numeric(ly[ind]) + as.numeric(ry[ind]))) / 2
    centerx = c(centerx,centx)
    centery = c(centery,centy)
  }
    #Centerx and Centery only contain the center point of the octopuses position for the indexes during the motion being analyzed, thus to use this set one must just run through it with a counter and not with the standard indexes or frame numbers.
  
  #Calculate total dis
  total_movement_dis = 0
  
  for (l in 1:(length(centerx)-1)){
    dx = as.numeric(centerx[l+1]) - as.numeric(centerx[l])
    dy = as.numeric(centery[l+1]) - as.numeric(centery[l])
  
    dis = sqrt((dx^2) + (dy^2))
    total_movement_dis =+ dis
  }

  #Find start_end coors of octo and crab
  crab_start_coors = c(as.numeric(current_crab_coors_file$X10[start_index]),as.numeric(current_crab_coors_file$Y10[start_index]))
  oc_start_coors = c(as.numeric(centerx[1]),as.numeric(centery[1]))
  oc_end_coors = c(as.numeric(centerx[length(centerx)]),as.numeric(centery[length(centery)]))

  #Find Bearing Change
  ideal_angle = atan2((crab_start_coors[2]-oc_start_coors[2]),(crab_start_coors[1]-oc_start_coors[1]))
  real_angle = atan2((oc_end_coors[2]-oc_start_coors[2]),(oc_end_coors[1]-oc_start_coors[1]))
  real_vs_ideal = ideal_angle - real_angle  #this factor will show the direction to which the real was left or right of ideal
  
  bearing_change = real_vs_ideal
  
  #Calculate Duration, Speed and Speed per Bodylength
  
  duration = (as.numeric(end_frame) - as.numeric(start_frame)) / 60
  
  mantle_dex = mantle_indecies$INDEX[mantle_indecies$OC==ocnum]
  speed = (total_movement_dis / duration)
  speed_per_bodylength = speed / mantle_dex
  #########
  
  #read in processed data
  proc_dat_name = paste0(WORKD,"\\Processed Data\\Full Video Results\\",DATE,"\\Processed_",DATE,"_O",ocnum,".csv")
  proc_dat = read.csv(proc_dat_name)
  
  #Find Degree of Directness
  Movdir_vs_Crab = c()
  move_ind = 1
  for (i in movement_indecies){
    if (i != movement_indecies[length(movement_indecies)]){
      ideal_a = atan2((as.numeric(current_crab_coors_file$Y10[i]) - centery[move_ind]),(as.numeric(current_crab_coors_file$X10[i]) -   centerx[move_ind]))
      Directness_diff = ideal_a - proc_dat$Dir_of_Movement[i] 
      Movdir_vs_Crab = c(Movdir_vs_Crab, Directness_diff)
      move_ind = move_ind + 1
    }  
  }
  avg_movdir_vs_crab = sum(Movdir_vs_Crab) / length(Movdir_vs_Crab)
  #collect bearing_movdir_diff for relevant frames
  ##Using start_end index, but minus one for end, bc the processed data represents differences between two frames
  bear_movedir_dif = c()
  for (i in movement_indecies){
    if (i != movement_indecies[length(movement_indecies)]){
      bear_movedir_dif = c(bear_movedir_dif, proc_dat$Bearing_Movedir_Dif[i])
    } 
  }
  
  bear_movedir_dif_dif = c()
  for (bear in 1:length(bear_movedir_dif)){
    dif = bear_movedir_dif[bear] - bear_movedir_dif[bear - 1]
    bear_movedir_dif_dif = c(bear_movedir_dif_dif, dif)
  }
    
  
  avg_bear_movedir_dif = sum(bear_movedir_dif) / length(bear_movedir_dif)
  
  avg_bear_movedir_dif_dif = sum(bear_movedir_dif_dif) / length(bear_movedir_dif_dif)
  
  ############
  return(c(total_movement_dis,bearing_change,duration,avg_bear_movedir_dif,avg_bear_movedir_dif_dif,speed,speed_per_bodylength,avg_movdir_vs_crab))
}
```

##currently logging 2 dif_difs

```{r}
per_date_loop = function(this_date){
  date_batch = c()
  
  date = c()
  movement_type = c()
  oc_ID = c()
  duration = c()
  total_movement_dis = c()
  speed = c()
  speed_per_bodylength = c()
  angle_dev = c()
  avg_bear_head_dif = c()
  avg_bear_head_dif_dif = c()
  avg_head_vs_crab = c()
  
  #make a list of the indecies in S_E_frames that relate to events from current date
  for (i in 1:length(start_end_frames$DATE)){
    if (start_end_frames$DATE[i] == this_date){
      date_batch = c(date_batch,i)
    }
  }

  #for each index: create a table of (date,movement_type,oc_num,tot_dis,ang_dev)
  for (j in 1:length(date_batch)){
    #returns (tot_move_dis,angle_dev) 
    path_dev = path_deviance(this_date,date_batch,j)
    
    total_movement_dis = c(total_movement_dis,path_dev[1])
    speed = c(speed,path_dev[6])
    speed_per_bodylength = c(speed_per_bodylength,path_dev[7])
    angle_dev = c(angle_dev,path_dev[2])
    oc_ID = c(oc_ID,start_end_frames$OCNUM[date_batch[j]])
    date = c(date,this_date)
    movement_type = c(movement_type,start_end_frames$MOVEMENT.TYPE[date_batch[j]])
    duration = c(duration,path_dev[3])
    avg_bear_head_dif = c(avg_bear_head_dif,path_dev[4])
    avg_bear_head_dif_dif = c(avg_bear_head_dif_dif,path_dev[5])
    avg_head_vs_crab = c(avg_head_vs_crab, path_dev[8])
    
    path_analysis_results = data.frame(date,oc_ID,movement_type,total_movement_dis,duration,speed,speed_per_bodylength,angle_dev,avg_bear_head_dif,avg_bear_head_dif_dif,avg_head_vs_crab)  
  }
  
  write.csv(path_analysis_results,paste0(WORKD,"\\Processed Data\\Path Analysis Results\\PA_Results_",this_date,".csv"))
}
```

```{r}
for (d in 1:length(datelist_u)){
  per_date_loop(datelist_u[d])
}
```

